[2024-10-06T19:12:58.203+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_pipeline.insert_data_to_db scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-10-06T19:12:58.212+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_pipeline.insert_data_to_db scheduled__2024-01-01T00:00:00+00:00 [queued]>
[2024-10-06T19:12:58.213+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-10-06T19:12:58.228+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): insert_data_to_db> on 2024-01-01 00:00:00+00:00
[2024-10-06T19:12:58.232+0000] {standard_task_runner.py:57} INFO - Started process 116 to run task
[2024-10-06T19:12:58.236+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flight_data_pipeline', 'insert_data_to_db', 'scheduled__2024-01-01T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/flights_dag.py', '--cfg-path', '/tmp/tmphpukb6ru']
[2024-10-06T19:12:58.238+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask insert_data_to_db
[2024-10-06T19:12:58.257+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-06T19:12:58.297+0000] {task_command.py:416} INFO - Running <TaskInstance: flight_data_pipeline.insert_data_to_db scheduled__2024-01-01T00:00:00+00:00 [running]> on host ea71d0098a44
[2024-10-06T19:12:58.408+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_data_pipeline' AIRFLOW_CTX_TASK_ID='insert_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-01-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-01T00:00:00+00:00'
[2024-10-06T19:12:58.433+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flights_dag.py", line 77, in upload_to_db
    for flight, value in collected_data.iterrows():
AttributeError: 'NoneType' object has no attribute 'iterrows'
[2024-10-06T19:12:58.442+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=flight_data_pipeline, task_id=insert_data_to_db, execution_date=20240101T000000, start_date=20241006T191258, end_date=20241006T191258
[2024-10-06T19:12:58.455+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task insert_data_to_db ('NoneType' object has no attribute 'iterrows'; 116)
[2024-10-06T19:12:58.500+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-06T19:12:58.523+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
