[2024-10-06T19:36:06.702+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_data_pipeline.upload_to_db scheduled__2024-10-05T00:00:00+00:00 [queued]>
[2024-10-06T19:36:06.715+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_data_pipeline.upload_to_db scheduled__2024-10-05T00:00:00+00:00 [queued]>
[2024-10-06T19:36:06.716+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2024-10-06T19:36:06.734+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): upload_to_db> on 2024-10-05 00:00:00+00:00
[2024-10-06T19:36:06.743+0000] {standard_task_runner.py:57} INFO - Started process 52 to run task
[2024-10-06T19:36:06.747+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flight_data_pipeline', 'upload_to_db', 'scheduled__2024-10-05T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/flights_dag.py', '--cfg-path', '/tmp/tmp8_ves7t4']
[2024-10-06T19:36:06.750+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask upload_to_db
[2024-10-06T19:36:06.772+0000] {logging_mixin.py:154} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-10-06T19:36:06.820+0000] {task_command.py:416} INFO - Running <TaskInstance: flight_data_pipeline.upload_to_db scheduled__2024-10-05T00:00:00+00:00 [running]> on host 2140475db266
[2024-10-06T19:36:06.926+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_data_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-10-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-05T00:00:00+00:00'
[2024-10-06T19:36:07.050+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flights_dag.py", line 77, in upload_to_db
    cursor.execute(
psycopg2.errors.NotNullViolation: null value in column "flight_number" of relation "testdata" violates not-null constraint
DETAIL:  Failing row contains (2024-10-07, active, Weipa, Australia/Brisbane, Cairns, Australia/Brisbane, 1, empty, null).

[2024-10-06T19:36:07.061+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=flight_data_pipeline, task_id=upload_to_db, execution_date=20241005T000000, start_date=20241006T193606, end_date=20241006T193607
[2024-10-06T19:36:07.073+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 100 for task upload_to_db (null value in column "flight_number" of relation "testdata" violates not-null constraint
DETAIL:  Failing row contains (2024-10-07, active, Weipa, Australia/Brisbane, Cairns, Australia/Brisbane, 1, empty, null).
; 52)
[2024-10-06T19:36:07.093+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-10-06T19:36:07.113+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
